# Generated by rust2rpm 9
%bcond_without check
%global debug_package %{nil}

%global crate proptest

Name:           rust-%{crate}
Version:        0.9.4
Release:        1%{?dist}
Summary:        Hypothesis-like property-based testing and shrinking

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/proptest
Source:         %{crates_source}
# Initial patched metadata
# * TODO: Send PR, Exclude unneeded files
Patch0:         proptest-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(bit-set/default) >= 0.5.0 with crate(bit-set/default) < 0.6.0)
BuildRequires:  (crate(bitflags/default) >= 1.0.1 with crate(bitflags/default) < 2.0.0)
BuildRequires:  (crate(byteorder) >= 1.2.3 with crate(byteorder) < 2.0.0)
BuildRequires:  (crate(byteorder/std) >= 1.2.3 with crate(byteorder/std) < 2.0.0)
BuildRequires:  (crate(lazy_static/default) >= 1.2.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(num-traits) >= 0.2.2 with crate(num-traits) < 0.3.0)
BuildRequires:  (crate(num-traits/std) >= 0.2.2 with crate(num-traits/std) < 0.3.0)
BuildRequires:  (crate(quick-error/default) >= 1.2.1 with crate(quick-error/default) < 2.0.0)
BuildRequires:  (crate(rand/alloc) >= 0.6.0 with crate(rand/alloc) < 0.7.0)
BuildRequires:  (crate(rand/i128_support) >= 0.6.0 with crate(rand/i128_support) < 0.7.0)
BuildRequires:  (crate(rand/std) >= 0.6.0 with crate(rand/std) < 0.7.0)
BuildRequires:  (crate(rand_chacha/default) >= 0.1.0 with crate(rand_chacha/default) < 0.2.0)
BuildRequires:  (crate(rand_xorshift/default) >= 0.1.0 with crate(rand_xorshift/default) < 0.2.0)
BuildRequires:  (crate(regex-syntax/default) >= 0.6.0 with crate(regex-syntax/default) < 0.7.0)
BuildRequires:  (crate(rusty-fork) >= 0.2.1 with crate(rusty-fork) < 0.3.0)
BuildRequires:  (crate(rusty-fork/timeout) >= 0.2.1 with crate(rusty-fork/timeout) < 0.3.0)
BuildRequires:  (crate(tempfile/default) >= 3.0.0 with crate(tempfile/default) < 4.0.0)
%if %{with check}
BuildRequires:  (crate(regex/default) >= 1.0.0 with crate(regex/default) < 2.0.0)
%endif
%endif

%global _description %{expand:
Hypothesis-like property-based testing and shrinking.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+atomic64bit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic64bit-devel %{_description}

This package contains library source intended for building other packages
which use "atomic64bit" feature of "%{crate}" crate.

%files       -n %{name}+atomic64bit-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+bit-set-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bit-set-devel %{_description}

This package contains library source intended for building other packages
which use "bit-set" feature of "%{crate}" crate.

%files       -n %{name}+bit-set-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+break-dead-code-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+break-dead-code-devel %{_description}

This package contains library source intended for building other packages
which use "break-dead-code" feature of "%{crate}" crate.

%files       -n %{name}+break-dead-code-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+default-code-coverage-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-code-coverage-devel %{_description}

This package contains library source intended for building other packages
which use "default-code-coverage" feature of "%{crate}" crate.

%files       -n %{name}+default-code-coverage-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fork-devel %{_description}

This package contains library source intended for building other packages
which use "fork" feature of "%{crate}" crate.

%files       -n %{name}+fork-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages
which use "lazy_static" feature of "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+quick-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quick-error-devel %{_description}

This package contains library source intended for building other packages
which use "quick-error" feature of "%{crate}" crate.

%files       -n %{name}+quick-error-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+regex-syntax-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-syntax-devel %{_description}

This package contains library source intended for building other packages
which use "regex-syntax" feature of "%{crate}" crate.

%files       -n %{name}+regex-syntax-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+rusty-fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rusty-fork-devel %{_description}

This package contains library source intended for building other packages
which use "rusty-fork" feature of "%{crate}" crate.

%files       -n %{name}+rusty-fork-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages
which use "tempfile" feature of "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+timeout-devel %{_description}

This package contains library source intended for building other packages
which use "timeout" feature of "%{crate}" crate.

%files       -n %{name}+timeout-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages
which use "unstable" feature of "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jun 09 13:43:04 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.4-1
- Update to 0.9.4

* Mon Apr 29 07:08:16 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.3-1
- Update to 0.9.3

* Sat Apr 27 12:08:50 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.2-1
- Update to 0.9.2

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.7-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Dec 15 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-4
- Bump rand to 0.6

* Sun Dec 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-3
- Rebuild

* Sun Dec 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-2
- Run tests in infrastructure

* Sun Dec 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-1
- Initial package
