# Generated by rust2rpm
# * Tests are run in infrastructure
%bcond_with check
%global debug_package %{nil}

%global crate proptest

Name:           rust-%{crate}
Version:        0.8.7
Release:        2%{?dist}
Summary:        Hypothesis-like property-based testing and shrinking

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/proptest
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No nightly
# * Exclude unneeded files
Patch0:         proptest-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(bit-set/default) >= 0.5.0 with crate(bit-set/default) < 0.6.0)
BuildRequires:  (crate(bitflags/default) >= 1.0.1 with crate(bitflags/default) < 2.0.0)
BuildRequires:  (crate(byteorder) >= 1.2.3 with crate(byteorder) < 2.0.0)
BuildRequires:  (crate(byteorder/std) >= 1.2.3 with crate(byteorder/std) < 2.0.0)
BuildRequires:  (crate(lazy_static) >= 1.0.0 with crate(lazy_static) < 2.0.0)
BuildRequires:  (crate(num-traits) >= 0.2.2 with crate(num-traits) < 0.3.0)
BuildRequires:  (crate(num-traits/std) >= 0.2.2 with crate(num-traits/std) < 0.3.0)
BuildRequires:  (crate(quick-error/default) >= 1.2.1 with crate(quick-error/default) < 2.0.0)
BuildRequires:  (crate(rand/alloc) >= 0.5.0 with crate(rand/alloc) < 0.6.0)
BuildRequires:  (crate(rand/i128_support) >= 0.5.0 with crate(rand/i128_support) < 0.6.0)
BuildRequires:  (crate(rand/std) >= 0.5.0 with crate(rand/std) < 0.6.0)
BuildRequires:  (crate(regex-syntax/default) >= 0.6.0 with crate(regex-syntax/default) < 0.7.0)
BuildRequires:  (crate(rusty-fork) >= 0.2.1 with crate(rusty-fork) < 0.3.0)
BuildRequires:  (crate(rusty-fork/timeout) >= 0.2.1 with crate(rusty-fork/timeout) < 0.3.0)
BuildRequires:  (crate(tempfile/default) >= 3.0.0 with crate(tempfile/default) < 4.0.0)
%if %{with check}
BuildRequires:  (crate(regex/default) >= 1.0.0 with crate(regex/default) < 2.0.0)
%endif

%global _description \
Hypothesis-like property-based testing and shrinking.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+bit-set-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bit-set-devel %{_description}

This package contains library source intended for building other packages
which use "bit-set" feature of "%{crate}" crate.

%files       -n %{name}+bit-set-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fork-devel %{_description}

This package contains library source intended for building other packages
which use "fork" feature of "%{crate}" crate.

%files       -n %{name}+fork-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+quick-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quick-error-devel %{_description}

This package contains library source intended for building other packages
which use "quick-error" feature of "%{crate}" crate.

%files       -n %{name}+quick-error-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+regex-syntax-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-syntax-devel %{_description}

This package contains library source intended for building other packages
which use "regex-syntax" feature of "%{crate}" crate.

%files       -n %{name}+regex-syntax-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+rusty-fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rusty-fork-devel %{_description}

This package contains library source intended for building other packages
which use "rusty-fork" feature of "%{crate}" crate.

%files       -n %{name}+rusty-fork-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages
which use "tempfile" feature of "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+timeout-devel %{_description}

This package contains library source intended for building other packages
which use "timeout" feature of "%{crate}" crate.

%files       -n %{name}+timeout-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages
which use "unstable" feature of "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Dec 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-2
- Run tests in infrastructure

* Sun Dec 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.7-1
- Initial package
